### Get Persons
http://localhost:3001/api/persons

### Get infos
http://localhost:3001/info

### Get Person infos
http://localhost:3001/api/persons/633a062461acbbc0a3802a5d

### Get unknown person infos (404)
http://localhost:3001/api/persons/633a060261acbbc0a3802a59

### Get person with malformed id (400)
http://localhost:3001/api/persons/633

### Delete person (idempotent)
delete http://localhost:3001/api/persons/633a062461acbbc0a3802a5d

### Delete unknown person (idempotent)
delete http://localhost:3001/api/persons/633a060261acbbc0a3802a58

### Delete with malformed id
delete http://localhost:3001/api/persons/633

### Create new person
POST http://localhost:3001/api/persons
Content-type: application/json

{
    "name": "Marc BUFALO",
    "phone": "457-78648-5745648"
}

### Create new person without required arguments
POST http://localhost:3001/api/persons
Content-type: application/json

{
    "name": "John Doe"
}

### Update person
PUT http://localhost:3001/api/persons/633a0fb2a73c3b80278a29di
Content-type: application/json

{
    "name": "Marc BUFALO (edited)",
    "phone": "123-456789"
}

### Unknown endpoint
GET http://localhost:3001/api/nobody