# Get Persons
http://localhost:3001/api/persons

###

# Get infos
http://localhost:3001/info

### 

# Get Person infos
http://localhost:3001/api/persons/633a060261acbbc0a3802a58

###

# Get unknown person infos (404)
http://localhost:3001/api/persons/633a060261acbbc0a3802a59

### 

# Delete person (idempotent)
delete http://localhost:3001/api/persons/633a060261acbbc0a3802a58

###

# Delete unknown person (idempotent)
delete http://localhost:3001/api/persons/633a060261acbbc0a3802a58

###

# Create new person

POST http://localhost:3001/api/persons
Content-type: application/json

{
    "name": "Marc BUFALO",
    "phone": "457-78648-5745648"
}

###

# Create new person without required arguments

POST http://localhost:3001/api/persons
Content-type: application/json

{
    "name": "John Doe"
}

###

# Unknown endpoint
GET http://localhost:3001/api/nobody